version: 2
jobs:
    build:
        machine:
            node:
                version: 6.0.0
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'npm install -g npm@latest'
            - restore_cache:
                key: v25-dependencies-{{ checksum "package.json" }}
            - run:
                name: Install_npm
                command: npm install
            - save_cache:
                key: v25-dependencies-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: Test
                command: npm run test:ci
            - run:
                name: Generate code coverage
                command: './node_modules/.bin/nyc report --reporter=text-lcov'
            - store_artifacts:
                path: test-results.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
             - store_test_results:
                path: test-results.xml
            
workflows:
  version: 2
  build:
    jobs:
      - build:
          requires:
            - build
          filters:
            branches:
              only: master
                