version: 2
jobs:
    build:
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest
            - run:
                name: install codeclimate-test-reporter
                command: npm install -g codeclimate-test-reporter
            - run:
                name: coverage info
                command: codeclimate-test-reporter < coverage/lcov.info
            
    
    test:
        steps:
            - checkout
            - run:
                name: Test
                command: npm test -- --coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
                