version: 2
jobs:
    build:
        machine:
            node:
                version: 6.0.0
        steps:
            - checkout
            - run:
                name: Update npm
                command: npm install -g npm@latest           
    
    test:
        machine:
            node:
                version: 6.0.0
        steps:
            - checkout
            - run:
                name: Test
                command: npm test
            - run:
                name: Generate code coverage
                command: './node_modules/.bin/nyc report --reporter=text-lcov'
            - store_artifacts:
                path: test-results.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
                